create table books(
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR NOT NULL,
    author_id BIGINT NOT NULL,
    page_count INT NOT NULL,
    isbn VARCHAR NOT NULL,

    FOREIGN KEY (author_id) REFERENCES authors(id)
);